modLoader="javafml"
loaderVersion="[45,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/anviaan/SimpleMango/issues"
[[mods]]
modId="bedrockplus"
version="1.5"
displayName="Bedrock Plus Mod"
updateJSONURL="https://anvian-page.netlify.app/forge/bedrockPlus.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bedrock-pus"
authors="anvian"
credits="PinhaColada2222"
description="Adds a new variant of bedrock, which can be combined with netherite armor."
displayTest="MATCH_VERSION"

[[dependencies.bedrockplus]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bedrockplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
